# Generated by Django 5.2.7 on 2025-10-31 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('symbol', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'verbose_name_plural': 'Currencies',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Locations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=4, max_digits=10)),
                ('date', models.DateField()),
                ('base_currency', models.ForeignKey(help_text='The currency this rate is against (the base).', on_delete=django.db.models.deletion.CASCADE, related_name='rates_as_base', to='configurations.currency')),
                ('target_currency', models.ForeignKey(help_text='The currency whose value is being quoted (the target).', on_delete=django.db.models.deletion.CASCADE, related_name='rates_as_target', to='configurations.currency')),
            ],
            options={
                'verbose_name_plural': 'Exchange Rates',
                'ordering': ['-date', 'base_currency__code', 'target_currency__code'],
                'unique_together': {('base_currency', 'target_currency', 'date')},
            },
        ),
    ]
